/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SonIslemlerRouteImport } from './routes/son-islemler'
import { Route as SearchReportRouteImport } from './routes/search-report'
import { Route as SearchByRecipeRouteImport } from './routes/search-by-recipe'
import { Route as OdemeRouteImport } from './routes/odeme'
import { Route as KayitRouteImport } from './routes/kayit'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GezintiRouteImport } from './routes/gezinti'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as IndexRouteImport } from './routes/index'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SonIslemlerRoute = SonIslemlerRouteImport.update({
  id: '/son-islemler',
  path: '/son-islemler',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchReportRoute = SearchReportRouteImport.update({
  id: '/search-report',
  path: '/search-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchByRecipeRoute = SearchByRecipeRouteImport.update({
  id: '/search-by-recipe',
  path: '/search-by-recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeRoute = OdemeRouteImport.update({
  id: '/odeme',
  path: '/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitRoute = KayitRouteImport.update({
  id: '/kayit',
  path: '/kayit',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GezintiRoute = GezintiRouteImport.update({
  id: '/gezinti',
  path: '/gezinti',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/gezinti': typeof GezintiRoute
  '/home': typeof HomeRoute
  '/kayit': typeof KayitRoute
  '/odeme': typeof OdemeRoute
  '/search-by-recipe': typeof SearchByRecipeRoute
  '/search-report': typeof SearchReportRoute
  '/son-islemler': typeof SonIslemlerRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/gezinti': typeof GezintiRoute
  '/home': typeof HomeRoute
  '/kayit': typeof KayitRoute
  '/odeme': typeof OdemeRoute
  '/search-by-recipe': typeof SearchByRecipeRoute
  '/search-report': typeof SearchReportRoute
  '/son-islemler': typeof SonIslemlerRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/gezinti': typeof GezintiRoute
  '/home': typeof HomeRoute
  '/kayit': typeof KayitRoute
  '/odeme': typeof OdemeRoute
  '/search-by-recipe': typeof SearchByRecipeRoute
  '/search-report': typeof SearchReportRoute
  '/son-islemler': typeof SonIslemlerRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayarlar'
    | '/gezinti'
    | '/home'
    | '/kayit'
    | '/odeme'
    | '/search-by-recipe'
    | '/search-report'
    | '/son-islemler'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayarlar'
    | '/gezinti'
    | '/home'
    | '/kayit'
    | '/odeme'
    | '/search-by-recipe'
    | '/search-report'
    | '/son-islemler'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/ayarlar'
    | '/gezinti'
    | '/home'
    | '/kayit'
    | '/odeme'
    | '/search-by-recipe'
    | '/search-report'
    | '/son-islemler'
    | '/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyarlarRoute: typeof AyarlarRoute
  GezintiRoute: typeof GezintiRoute
  HomeRoute: typeof HomeRoute
  KayitRoute: typeof KayitRoute
  OdemeRoute: typeof OdemeRoute
  SearchByRecipeRoute: typeof SearchByRecipeRoute
  SearchReportRoute: typeof SearchReportRoute
  SonIslemlerRoute: typeof SonIslemlerRoute
  SubscriptionRoute: typeof SubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/son-islemler': {
      id: '/son-islemler'
      path: '/son-islemler'
      fullPath: '/son-islemler'
      preLoaderRoute: typeof SonIslemlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-report': {
      id: '/search-report'
      path: '/search-report'
      fullPath: '/search-report'
      preLoaderRoute: typeof SearchReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-by-recipe': {
      id: '/search-by-recipe'
      path: '/search-by-recipe'
      fullPath: '/search-by-recipe'
      preLoaderRoute: typeof SearchByRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme': {
      id: '/odeme'
      path: '/odeme'
      fullPath: '/odeme'
      preLoaderRoute: typeof OdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit': {
      id: '/kayit'
      path: '/kayit'
      fullPath: '/kayit'
      preLoaderRoute: typeof KayitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gezinti': {
      id: '/gezinti'
      path: '/gezinti'
      fullPath: '/gezinti'
      preLoaderRoute: typeof GezintiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyarlarRoute: AyarlarRoute,
  GezintiRoute: GezintiRoute,
  HomeRoute: HomeRoute,
  KayitRoute: KayitRoute,
  OdemeRoute: OdemeRoute,
  SearchByRecipeRoute: SearchByRecipeRoute,
  SearchReportRoute: SearchReportRoute,
  SonIslemlerRoute: SonIslemlerRoute,
  SubscriptionRoute: SubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
