// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).

declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface PlaywrightCredentials {
  username: string;
  password: string;
}

interface PlaywrightNavigationResult {
  success: boolean;
  currentUrl?: string;
  redirectedToLogin?: boolean;
  error?: string;
}

interface PlaywrightLoginResult {
  success: boolean;
  currentUrl?: string;
  redirectedToLogin?: boolean;
  error?: string;
}

interface PlaywrightSearchResult {
  success: boolean;
  prescriptionData?: unknown;
  currentUrl?: string;
  error?: string;
}

interface PlaywrightDateRangeResult {
  success: boolean;
  prescriptions?: string[];
  currentUrl?: string;
  error?: string;
}

interface PlaywrightInitializeResult {
  success: boolean;
  error?: string;
}

interface PlaywrightCredentialsResult {
  credentials: PlaywrightCredentials | null;
}

interface PlaywrightHasCredentialsResult {
  hasCredentials: boolean;
}

interface PlaywrightDebugResult {
  debugMode: boolean;
}

interface BrowserInstallProgress {
  status: "checking" | "installing" | "done" | "error";
  message: string;
  progress?: number;
}

declare global {
  interface Window {
    playwrightAPI: {
      initialize: () => Promise<PlaywrightInitializeResult>;
      ensureBrowsers: () => Promise<PlaywrightInitializeResult>;
      onBrowserInstallProgress: (callback: (progress: BrowserInstallProgress) => void) => () => void;
      navigate: (url: string) => Promise<PlaywrightNavigationResult>;
      login: (credentials: PlaywrightCredentials) => Promise<PlaywrightLoginResult>;
      navigateToSGK: () => Promise<PlaywrightNavigationResult>;
      searchPrescription: (prescriptionNumber: string) => Promise<PlaywrightSearchResult>;
      searchByDateRange: (startDate: string, endDate: string) => Promise<PlaywrightDateRangeResult>;
      getCurrentUrl: () => Promise<string | null>;
      isReady: () => Promise<boolean>;
      close: () => Promise<void>;
      setDebugMode: (enabled: boolean) => Promise<void>;
      getDebugMode: () => Promise<PlaywrightDebugResult>;
      restart: () => Promise<void>;
      setCredentials: (credentials: PlaywrightCredentials) => Promise<void>;
      getStoredCredentials: () => Promise<PlaywrightCredentialsResult>;
      hasCredentials: () => Promise<PlaywrightHasCredentialsResult>;
      autoLogin: () => Promise<PlaywrightLoginResult>;
    };
  }
}
