declare module "*.svg" {
  const src: string;
  export default src;
}

declare module "*.svg?raw" {
  const content: string;
  export default content;
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).

declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface PlaywrightCredentials {
  username: string;
  password: string;
}

interface PlaywrightNavigationResult {
  success: boolean;
  currentUrl?: string;
  redirectedToLogin?: boolean;
  error?: string;
}

interface PlaywrightLoginResult {
  success: boolean;
  currentUrl?: string;
  redirectedToLogin?: boolean;
  error?: string;
}

interface PlaywrightSearchResult {
  success: boolean;
  prescriptionData?: unknown;
  currentUrl?: string;
  error?: string;
}

interface PlaywrightDateRangeResult {
  success: boolean;
  prescriptions?: string[];
  currentUrl?: string;
  error?: string;
}

interface PlaywrightInitializeResult {
  success: boolean;
  error?: string;
}

interface PlaywrightCredentialsResult {
  credentials: PlaywrightCredentials | null;
}

interface PlaywrightHasCredentialsResult {
  hasCredentials: boolean;
}

interface PlaywrightDebugResult {
  debugMode: boolean;
}

interface BrowserInstallProgress {
  status: "checking" | "installing" | "done" | "error";
  message: string;
  progress?: number;
}

interface SecureStorageCredentials {
  username: string;
  password: string;
  loginTime: string;
}

interface SecureStorageResult {
  success: boolean;
  error?: string;
}

interface SecureStorageGetResult {
  success: boolean;
  credentials: SecureStorageCredentials | null;
  error?: string;
}

interface SecureStorageHasResult {
  success: boolean;
  hasCredentials: boolean;
}

declare global {
  interface Window {
    playwrightAPI: {
      initialize: () => Promise<PlaywrightInitializeResult>;
      ensureBrowsers: () => Promise<PlaywrightInitializeResult>;
      onBrowserInstallProgress: (callback: (progress: BrowserInstallProgress) => void) => () => void;
      navigate: (url: string) => Promise<PlaywrightNavigationResult>;
      login: (credentials: PlaywrightCredentials) => Promise<PlaywrightLoginResult>;
      navigateToSGK: () => Promise<PlaywrightNavigationResult>;
      searchPrescription: (prescriptionNumber: string) => Promise<PlaywrightSearchResult>;
      searchByDateRange: (startDate: string, endDate: string) => Promise<PlaywrightDateRangeResult>;
      getCurrentUrl: () => Promise<string | null>;
      isReady: () => Promise<boolean>;
      close: () => Promise<void>;
      setDebugMode: (enabled: boolean) => Promise<void>;
      getDebugMode: () => Promise<PlaywrightDebugResult>;
      restart: () => Promise<void>;
      setCredentials: (credentials: PlaywrightCredentials) => Promise<void>;
      getStoredCredentials: () => Promise<PlaywrightCredentialsResult>;
      hasCredentials: () => Promise<PlaywrightHasCredentialsResult>;
      autoLogin: () => Promise<PlaywrightLoginResult>;
    };
    captchaAPI: {
      solve: (base64Image: string) => Promise<{ success: boolean; code: string | null; error?: string }>;
    };
    secureStorage: {
      isAvailable: () => Promise<boolean>;
      setCredentials: (credentials: SecureStorageCredentials) => Promise<SecureStorageResult>;
      getCredentials: () => Promise<SecureStorageGetResult>;
      clearCredentials: () => Promise<SecureStorageResult>;
      hasCredentials: () => Promise<SecureStorageHasResult>;
    };
  }

  // Electron webview tag support in JSX
  namespace JSX {
    interface IntrinsicElements {
      webview: React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement> & {
          src?: string;
          partition?: string;
          preload?: string;
          allowpopups?: boolean;
          nodeintegration?: boolean;
          disablewebsecurity?: boolean;
        },
        HTMLElement
      >;
    }
  }
}
